[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Set the Node.js version Netlify should use
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200